import Head from 'next/head';

import { PokemonsGrid } from '../components/custom/pokemons-grid';
import { pokemonsApi } from '../features/pokemons/pokemons-api';
import { storeWrapper } from '../lib/redux/store';

export default function Home(props: any) {

  return (
    <div>
      <Head>
        <title>Nextjs - Redux</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>

        <PokemonsGrid />

      </main>

      <footer className="p-5 border-t-2">
        Nextjs - Redux
      </footer>
    </div >
  )
}

export const getStaticProps = storeWrapper.getStaticProps(store => async (context) => {

  await store.dispatch(pokemonsApi.endpoints.getPokemons.initiate(null));

  return {
    props: {},
    revalidate: 3600,
  }
})
